### ISSUE TITLE
Error on example

### ISSUE THREAD

**Issue by lautarodapin** [hishnash/hypermediachannels#2]
Not working 
```py
# serializers.py
class UserSerializer(HyperChannelsApiModelSerializer):
    class Meta:
        model = User
        fields = [
            "@id",
            "username",
        ]
```
```py
# consumers.py
class UserConsumer(ListModelMixin, GenericAsyncAPIConsumer):
    queryset = User.objects.all()
    serializer_class = UserSerializer



class DemultiplexerAsyncJson(AsyncJsonWebsocketDemultiplexer):
    applications = {
        "users":UserConsumer,
    }
```
```py
# routing.py
websocket_urlpatterns = [
    path('ws/', consumers.DemultiplexerAsyncJson.as_asgi())
]
```

Backlog
```
WebSocket HANDSHAKING /ws/ [127.0.0.1:57486]
Exception inside application: object.__init__() takes exactly one argument (the instance to initialize)
Traceback (most recent call last):
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/routing.py", line 150, in __call__
    return await application(
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channelsmultiplexer/demultiplexer.py", line 61, in __call__
    await future
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/asgiref/compatibility.py", line 33, in new_application
    instance = application(scope)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/djangochannelsrestframework/consumers.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/generic/websocket.py", line 159, in __init__
    super().__init__(*args, **kwargs)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

**Comment by lautarodapin** [comment]
I change the consumers file as follow:

```
class UserConsumer(ListModelMixin, GenericAsyncAPIConsumer):
    queryset = User.objects.all()
    serializer_class = UserSerializer



class DemultiplexerAsyncJson(AsyncJsonWebsocketDemultiplexer):
    applications = {
        "users":UserConsumer.as_asgi(), # <--- here
    }
```

But it throws the following error.
```

WebSocket HANDSHAKING /ws/ [127.0.0.1:57556]
WebSocket CONNECT /ws/ [127.0.0.1:57556]
Exception inside application: 'function' object has no attribute 'queryset'
Traceback (most recent call last):
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/routing.py", line 150, in __call__
    return await application(
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channelsmultiplexer/demultiplexer.py", line 61, in __call__
    await future
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/generic/websocket.py", line 196, in websocket_receive
    await self.receive(text_data=message["text"])
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/generic/websocket.py", line 259, in receive
    await self.receive_json(await self.decode_json(text_data), **kwargs)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/djangochannelsrestframework/consumers.py", line 160, in receive_json
    await self.handle_action(action, request_id=request_id, **content)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/djangochannelsrestframework/consumers.py", line 151, in handle_action
    await self.handle_exception(exc, action=action, request_id=request_id)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/djangochannelsrestframework/consumers.py", line 117, in handle_exception
    raise exc
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/djangochannelsrestframework/consumers.py", line 144, in handle_action
    response = await method(request_id=request_id, action=action, **kwargs)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/djangochannelsrestframework/decorators.py", line 64, in async_f
    result, status = await database_sync_to_async(func)(self, *args, **_kwargs)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/asgiref/sync.py", line 304, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/channels/db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/asgiref/sync.py", line 343, in thread_handler
    return func(*args, **kwargs)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/djangochannelsrestframework/mixins.py", line 25, in list
    return serializer.data, status.HTTP_200_OK
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/hypermediachannels/serializers.py", line 35, in to_representation
    return [
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/hypermediachannels/serializers.py", line 37, in <listcomp>
    super(HyperChannelsApiListSerializer, self).to_representation(item)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/hypermediachannels/fields.py", line 111, in to_representation
    stream_name, consumer = self.resolve(type(instance))
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/hypermediachannels/fields.py", line 69, in resolve
    stream_name, consumer = self._get_resolve(model)
  File "/home/lautaro/Documentos/channels_test/venv/lib/python3.8/site-packages/hypermediachannels/fields.py", line 80, in _get_resolve
    if consumer.queryset is None:
AttributeError: 'function' object has no attribute 'queryset'
WebSocket DISCONNECT /ws/ [127.0.0.1:57556]

```

**Comment by lautarodapin** [comment]
#3
